[package]
name = "leptos-tea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = "0.2"
paste = "1"
tracing = "0.1"

[dev-dependencies]
typed-builder = "0.14"